---
# defaults file for docker-compose

# Docker Compose options.
docker_install_compose: true
docker_compose_version: "2.2.0"
docker_compose_arch: x86_64
docker_compose_url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-Linux-{{ docker_compose_arch }}"
docker_compose_path: /usr/local/bin/docker-compose
